trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu 18.04'

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: 'Install Node.js'

  - script: npm install && npm install -g @angular/cli
    displayName: 'Install dependencies'

  - task: NodeTool@0
    displayName: 'Test Angular'
    inputs:
      command: custom
      customCommand: ng test --watch false --source-map true --code-coverage
      workingDir: 'src'

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'sonar-new'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
          sonar.organization=lqc-github
            sonar.projectKey=sonar-angular-example
            sonar.projectName=SonarQube + Angular Example
            sonar.projectVersion=1.0.0
            sonar.sourceEncoding=UTF-8
            sonar.sources=src/
        sonar.typescript.lcov.reportPaths=coverage/lcov.info
            sonar.coverage.exclusions=**/*.spec.ts,src/environments/*,src/karma.conf.js		
  
  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'
