# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Setup Environment'

- script: npm install
  displayName: 'Install Dependencies'

- script: npx ng build --prod
  displayName: 'Build'

- script: npm install -g tslint
  displayName: 'Code Analysis'

- script: tslint -c tslint.json 'src/*.ts'
  displayName: 'Code Analysis report'

- task: SonarQubePrepare@4
  inputs:
      SonarQube: 'sonar-new'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
          sonar.organization=lqc-github
            sonar.projectKey=Angular-Js-new_Angular-Js-new
            sonar.projectName=SonarQube + Angular Example
            sonar.projectVersion=1.0.0
            sonar.sourceEncoding=UTF-8
            sonar.sources=src/
            sonar.typescript.tslint.reportPaths=src/tslint.json
        sonar.typescript.lcov.reportPaths=coverage/lcov.info
            sonar.coverage.exclusions=**/*.spec.ts,src/environments/*,src/karma.conf.js		
  
- task: SonarQubePublish@4
  inputs:
      pollingTimeoutSec: '300'